# Generated by Django 5.2.6 on 2025-09-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_customuser_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='customuser',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to='albums/covers/'),
        ),
    ]
