# Generated by Django 5.2.6 on 2025-09-30 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_remove_customuser_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to='covers'),
        ),
    ]
