# Generated by Django 5.2.6 on 2025-10-01 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_alter_customuser_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('singer', 'Singer'), ('normal', 'Normal')], default='normal', max_length=10),
        ),
    ]
