# Generated by Django 5.2.6 on 2025-10-02 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0006_customuser_bio_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('singer', 'Singer'), ('normal', 'Normal')], max_length=10),
        ),
    ]
