# Generated by Django 5.2.6 on 2025-10-02 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0007_alter_customuser_bio_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bio',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
