# Generated by Django 5.2.6 on 2025-10-03 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0012_alter_customuser_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='bio',
            new_name='album_description',
        ),
    ]
