# Generated by Django 5.2.6 on 2025-10-03 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0014_customuser_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='followers',
        ),
    ]
