# Generated by Django 5.2.6 on 2025-10-03 10:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0015_remove_customuser_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='unfollowed',
            field=models.ManyToManyField(blank=True, related_name='unfollowed_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
