# Generated by Django 5.2.6 on 2025-10-04 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0016_customuser_following_customuser_unfollowed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='album_description',
            new_name='Bio',
        ),
    ]
