# Generated by Django 5.2.6 on 2025-10-06 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0018_passwordreset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='cover_image',
            new_name='profile_image',
        ),
    ]
