# Generated by Django 5.2.6 on 2025-10-08 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0019_rename_cover_image_customuser_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='following',
            new_name='follow',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='unfollowed',
            new_name='unfollow',
        ),
    ]
