# Generated by Django 5.2.6 on 2025-10-08 12:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0020_rename_following_customuser_follow_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='follow',
            field=models.ManyToManyField(blank=True, related_name='follow_self', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='unfollow',
            field=models.ManyToManyField(blank=True, related_name='unfollow_self', to=settings.AUTH_USER_MODEL),
        ),
    ]
