# Generated by Django 5.2.6 on 2025-10-03 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
        ('song', '0002_rename_album_song_album_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='album_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='song', to='album.album'),
        ),
    ]
