# Generated by Django 5.2.6 on 2025-10-06 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0004_alter_song_song_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='audio_file',
        ),
    ]
