# Generated by Django 5.2.6 on 2025-10-05 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
