# Generated by Django 5.2.6 on 2025-10-05 08:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0003_alter_playlist_playlist_name'),
        ('song', '0004_alter_song_song_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='playlist',
            constraint=models.UniqueConstraint(fields=('playlist_name', 'created_by'), name='unique_playlist_per_user'),
        ),
    ]
