# Generated by Django 5.2.6 on 2025-10-05 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0004_playlist_unique_playlist_per_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='playlist_name',
            field=models.CharField(max_length=100),
        ),
    ]
