# Generated by Django 5.2.6 on 2025-10-07 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_alter_album_album_name_album_unique_album_per_singer'),
        ('playlist', '0005_alter_playlist_playlist_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='albums',
            field=models.ManyToManyField(blank=True, related_name='playlists', to='album.album'),
        ),
    ]
